const path=require('path');
const fs=require('fs');
const express=require('express');
const session=require('express-session');
const pgSession=require('connect-pg-simple')(session);
const multer=require('multer');
const {pool,query,initDb}=require('./db');
require('dotenv').config();
const app=express();
const PORT=Number(process.env.PORT||3000);
const uploadDir=path.join(__dirname,'..','public','assets','uploads');
fs.mkdirSync(uploadDir,{recursive:true});
const storage=multer.diskStorage({destination:uploadDir,filename:(req,file,cb)=>{const ext=path.extname(file.originalname).toLowerCase(); cb(null,Date.now()+'-'+Math.random().toString(36).slice(2,9)+ext)}});
const upload=multer({storage,limits:{fileSize:5*1024*1024},fileFilter:(req,file,cb)=>{if(/^image\/(jpeg|png|webp|gif|svg\+xml)$/.test(file.mimetype)) cb(null,true); else cb(new Error('Only image files are allowed'))}});
app.set('trust proxy',1); app.use(express.json({limit:'1mb'})); app.use(express.urlencoded({extended:true}));
const sessionConfig={secret:process.env.SESSION_SECRET||'dev-secret',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:1000*60*60*24*7}}; if(process.env.NODE_ENV==='production'){sessionConfig.store=new pgSession({pool,tableName:'user_sessions',createTableIfMissing:true}); console.log('Session store: PostgreSQL')}else{console.log('Session store: memory (local development)')} app.use(session(sessionConfig));
app.use(express.static(path.join(__dirname,'..','public')));
const admin=(req,res,next)=>req.session?.admin?next():res.status(401).json({error:'Unauthorized'});
app.get('/api/health',async(req,res)=>{try{await query('SELECT 1');res.json({ok:true,database:'connected'})}catch(e){res.status(503).json({ok:false,error:'Database unavailable'})}});
app.get('/api/profile',async(req,res)=>{const r=await query('SELECT * FROM profile WHERE id=1');res.json(r.rows[0])});
app.get('/api/works',async(req,res)=>{const r=await query('SELECT * FROM works ORDER BY featured DESC,created_at DESC');res.json(r.rows)});
app.get('/api/works/:slug',async(req,res)=>{const r=await query('SELECT * FROM works WHERE slug=$1',[req.params.slug]); if(!r.rowCount)return res.status(404).json({error:'Not found'});res.json(r.rows[0])});
app.post('/api/admin/login',async(req,res)=>{const {email,password}=req.body;if(email===process.env.ADMIN_EMAIL&&password===process.env.ADMIN_PASSWORD){req.session.admin={email};return res.json({ok:true})}res.status(401).json({error:'Invalid credentials'})});
app.post('/api/admin/logout',(req,res)=>req.session.destroy(()=>res.json({ok:true})));
app.get('/api/admin/me',admin,(req,res)=>res.json({email:req.session.admin.email}));
app.put('/api/admin/profile',admin,upload.single('image'),async(req,res)=>{const {name,title,bio,location}=req.body;let image=req.body.image_url||null;if(req.file)image='/assets/uploads/'+req.file.filename;const r=await query(`UPDATE profile SET name=COALESCE($1,name),title=COALESCE($2,title),bio=COALESCE($3,bio),location=COALESCE($4,location),image_url=COALESCE($5,image_url),updated_at=now() WHERE id=1 RETURNING *`,[name,title,bio,location,image]);res.json(r.rows[0])});
app.post('/api/admin/works',admin,upload.single('image'),async(req,res)=>{const {slug,title,category,summary,description,live_url,repo_url,featured}=req.body;let image=null;if(req.file)image='/assets/uploads/'+req.file.filename;const tech=(req.body.tech||'').split(',').map(x=>x.trim()).filter(Boolean);const r=await query(`INSERT INTO works(slug,title,category,summary,description,tech,live_url,repo_url,image_url,featured) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[slug,title,category,summary,description||summary,tech,live_url||null,repo_url||null,image,featured==='true']);res.status(201).json(r.rows[0])});
app.put('/api/admin/works/:id',admin,upload.single('image'),async(req,res)=>{const {title,category,summary,description,live_url,repo_url,featured}=req.body;let image=req.file?'/assets/uploads/'+req.file.filename:null;const tech=(req.body.tech||'').split(',').map(x=>x.trim()).filter(Boolean);const r=await query(`UPDATE works SET title=COALESCE($1,title),category=COALESCE($2,category),summary=COALESCE($3,summary),description=COALESCE($4,description),tech=$5,live_url=$6,repo_url=$7,image_url=COALESCE($8,image_url),featured=$9,updated_at=now() WHERE id=$10 RETURNING *`,[title,category,summary,description,tech,live_url||null,repo_url||null,image,featured==='true',req.params.id]);if(!r.rowCount)return res.status(404).json({error:'Not found'});res.json(r.rows[0])});
app.delete('/api/admin/works/:id',admin,async(req,res)=>{await query('DELETE FROM works WHERE id=$1',[req.params.id]);res.json({ok:true})});
app.get('/work/:slug',(req,res)=>res.sendFile(path.join(__dirname,'..','public','work.html'))); app.get('/admin/login',(req,res)=>res.sendFile(path.join(__dirname,'..','public','pages','admin-login.html')));
app.get('/admin',(req,res)=>res.sendFile(path.join(__dirname,'..','public','pages','admin.html')));
app.use((err,req,res,next)=>{console.error(err);res.status(400).json({error:err.message||'Request failed'})});
(async()=>{try{await initDb();app.listen(PORT,'0.0.0.0',()=>console.log(`Codex Inc portfolio running on port ${PORT}`))}catch(e){console.error(e);process.exit(1)}})();
